[package]
name = "shinkai_subscription_manager"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
chrono = { workspace = true }
futures = { workspace = true }
dashmap = "5.5.3"
bincode = "1.3.3"
serde_json = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
tokio = { workspace = true, features = ["full"] }
shinkai_message_primitives = { workspace = true }
shinkai_vector_resources = { workspace = true }
shinkai_vector_fs = { workspace = true }
shinkai_job_queue_manager = { workspace = true }
shinkai_db = { workspace = true }
reqwest = { workspace = true, features = [
    "json",
    "tokio-native-tls",
    "blocking",
    "stream",
] }
aws-types = "1.2.0"
aws-config = { version = "1.2.1", features = ["behavior-version-latest"] }
aws-sdk-s3 = { version = "1.24.0", features = ["behavior-version-latest"] }
urlencoding = "2.1.0"
thiserror = "1.0.50"
serde = { workspace = true, features = ["derive"] }
