[package]
name = "shinkai_subscription_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
chrono-tz = "0.5"
futures = "0.3.30"
dashmap = "5.5.3"
bincode = "1.3.3"
serde_json = "1.0.117"
chacha20poly1305 = "0.7.1"
ed25519-dalek = "2.1.0"
x25519-dalek = { version = "2.0.0", features = ["static_secrets"] }
uuid = { version = "1.6.1", features = ["v4"] }
tokio = { version = "1.36", features = ["full"] }
shinkai_message_primitives = { workspace = true }
shinkai_vector_resources = { workspace = true }
shinkai_vector_fs = { workspace = true }
shinkai_job_queue_manager = { workspace = true }
shinkai_db = { workspace = true }
reqwest = { version = "0.11.26", features = [
    "json",
    "tokio-native-tls",
    "blocking",
    "stream",
] }
aws-types = "1.2.0"
aws-config = { version = "1.2.1", features = ["behavior-version-latest"] }
aws-sdk-s3 = { version = "1.24.0", features = ["behavior-version-latest"] }
urlencoding = "2.1.0"
thiserror = "1.0.50"
lru = "0.7.0"

[dependencies.serde]
version = "1.0.188"
features = ["derive"]
