openapi: 3.0.3
info:
  title: shinkai_node
  description: ''
  contact:
    name: Nico Arqueros
    email: nico@shinkai.com
  license:
    name: ''
  version: 0.8.4
paths:
  /v2/add_shinkai_tool:
    post:
      tags:
      - crate
      operationId: add_shinkai_tool_handler
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShinkaiTool'
        required: true
      responses:
        '200':
          description: Successfully added Shinkai tool
          content:
            application/json:
              schema: {}
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
  /v2/get_shinkai_tool:
    get:
      tags:
      - crate
      operationId: get_shinkai_tool_handler
      parameters:
      - name: tool_name
        in: query
        description: Name of the Shinkai tool
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successfully retrieved Shinkai tool
          content:
            application/json:
              schema: {}
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
  /v2/list_all_shinkai_tools:
    get:
      tags:
      - crate
      operationId: list_all_shinkai_tools_handler
      responses:
        '200':
          description: Successfully listed all Shinkai tools
          content:
            application/json:
              schema: {}
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
  /v2/search_shinkai_tool:
    get:
      tags:
      - crate
      operationId: search_shinkai_tool_handler
      parameters:
      - name: query
        in: query
        description: Search query for Shinkai tools
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successfully searched Shinkai tools
          content:
            application/json:
              schema: {}
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'

  /v2/set_shinkai_tool:
    post:
      tags:
      - crate
      operationId: set_shinkai_tool_handler
      parameters:
      - name: tool_name
        in: query
        description: Key name of the Shinkai tool
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema: {}
        required: true
      responses:
        '200':
          description: Successfully set Shinkai tool
          content:
            text/plain:
              schema:
                type: boolean
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'

components:
  schemas:
    APIError:
      type: object
      required:
      - code
      - error
      - message
      properties:
        code:
          type: integer
          format: int32
          minimum: 0
        error:
          type: string
        message:
          type: string
    
tags:
- name: workflows
  description: Workflow API endpoints
