name: Build shinkai-node docker image

on:
  push:
    branches:
      - 'main'
      - 'devops'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-and-deploy:
    uses: dcSpark/shinkai-node/.github/workflows/build-workflow.yml@devops
    with:
      REGISTRY: dcspark
      REPOSITORY: shinkai-node
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      
  build-wasm-tests:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.wasm
          push: false # Set push to false to avoid pushing the image
          tags: wasm-tests # Replace with your Docker Hub username and repository name
