[package]
name = "shinkai-spreadsheet-llm"
version = "0.1.0"
edition = "2021"
authors.workspace = true

[dependencies]
async-trait = "0.1.74"
chrono = { workspace = true }
ndarray = "0.16.1"
regex = { workspace = true }

[dev-dependencies]
csv = "1.1.6"
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }
