max_width = 120
hard_tabs = false
tab_spaces = 4

imports_indent = "Block"
imports_layout = "Horizontal"

match_arm_blocks = true

trailing_comma = "Vertical"

comment_width = 140
wrap_comments = true
format_code_in_doc_comments = true

edition = "2021"