[package]
name = "shinkai_vector_fs"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
shinkai_message_primitives = { path = "../shinkai-message-primitives" }
shinkai_vector_resources = { workspace = true }
bincode = "1.3.3"
serde_json = { workspace = true }
rand = { workspace = true }
blake3 = { workspace = true }
tokio = { workspace = true, features = ["full"] }
chrono = { workspace = true }

[dependencies.rocksdb]
workspace = true
features = ["lz4"]

[dependencies.serde]
workspace = true
features = ["derive"]
