[package]
name = "shinkai_vector_fs"
version = "0.1.0"
edition = "2021"

[dependencies]
shinkai_message_primitives = { path = "../shinkai-message-primitives" }
shinkai_vector_resources = { workspace = true }
bincode = "1.3.3"
serde_json = "1.0.117"
rand = "=0.8"
blake3 = "1.2.0"
tokio = { version = "1.36", features = ["full"] }
chrono = "0.4"

[dependencies.rocksdb]
version = "0.22.0"
default-features = false
features = ["lz4"]

[dependencies.serde]
version = "1.0.188"
features = ["derive"]