[package]
name = "shinkai_sqlite"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
serde_json = { workspace = true }
chrono = { workspace = true }
rusqlite = { version = "0.32.1", features = ["bundled"] }
sqlite-vec = "0.1.3"
tokio = { workspace = true, features = ["full"] }
r2d2 = "0.8.10"
r2d2_sqlite = "0.25"
shinkai_tools_primitives = { workspace = true }
shinkai_vector_resources = { workspace = true }
shinkai_message_primitives = { workspace = true }
shinkai_sheet = { workspace = true }
reqwest = "0.11.27"
bincode = "1.3.3"
zerocopy = "0.8.9"
bytemuck = "1.7" 
thiserror = "2.0.3"
blake3 = { workspace = true }
hex = { workspace = true }
rand = { workspace = true }
x25519-dalek = { version = "2.0.0", features = ["static_secrets"] }
ed25519-dalek = "2.1.0"

[dependencies.serde]
workspace = true
features = ["derive"]

[dev-dependencies]
tempfile = "3.2"
rust_decimal = "1.17.0"