[package]
name = "shinkai_sqlite"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.117"
dashmap = "5.5.3"
chrono = "0.4"
regex = "1"
rusqlite = { version = "0.32.1", features = ["bundled"] }
sqlite-vec = "0.1.3"
tokio = { version = "1.36", features = ["full"] }
futures = "0.3.30"
r2d2 = "0.8.10"
r2d2_sqlite = "0.25"
uuid = { version = "1.6.1", features = ["v4"] }
shinkai_tools_primitives = { workspace = true }
shinkai_vector_resources = { workspace = true }
shinkai_message_primitives = { workspace = true }
reqwest = "0.11.26"
bincode = "1.3.3"
zerocopy = "0.8.9"
bytemuck = "1.7" 
thiserror = "2.0.3"

[dependencies.serde]
version = "1.0.188"
features = ["derive"]

[dev-dependencies]
tempfile = "3.2"