[package]
name = "shinkai_sqlite"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.117"
dashmap = "5.5.3"
chrono = "0.4"
regex = "1"
rusqlite = { version = "0.28.0", features = ["bundled"] } 
tokio = { version = "1.36", features = ["full"] }
futures = "0.3.30"
r2d2 = "0.8"
r2d2_sqlite = "0.21"
uuid = { version = "1.6.1", features = ["v4"] }

[dependencies.serde]
version = "1.0.188"
features = ["derive"]
