[package]
name = "shinkai_sqlite"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
serde_json = { workspace = true }
chrono = { workspace = true }
regex = { workspace = true }
rusqlite = { version = "0.32.1", features = ["bundled"] }
tokio = { workspace = true, features = ["full"] }
futures = { workspace = true }
r2d2 = "0.8.10"
r2d2_sqlite = "0.25"
uuid = { workspace = true, features = ["v4"] }
shinkai_tools_primitives = { workspace = true }

[dependencies.serde]
workspace = true
features = ["derive"]
