[package]
name = "shinkai_tools_primitives"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }
regex = { workspace = true }
shinkai_message_primitives = { workspace = true }
shinkai_vector_resources = { workspace = true }
reqwest = { workspace = true, features = [
    "json",
    "tokio-native-tls",
    "blocking",
    "stream",
] }
anyhow = { workspace = true }
shinkai_tools_runner = { workspace = true, features = ["built-in-tools"] }
serde = { workspace = true, features = ["derive"] }
