[package]
name = "shinkai_tools_primitives"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.117"
futures = "0.3.30"
tokio = { version = "1.36", features = ["full"] }
dashmap = "5.5.3"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.6.1", features = ["v4"] }
regex = "1"
shinkai_dsl = { workspace = true }
shinkai_message_primitives = { workspace = true }
shinkai_vector_resources = { workspace = true }
shinkai_db = { workspace = true }
async-channel = "1.6.1"
blake3 = "1.2.0"
reqwest = { version = "0.11.26", features = [
    "json",
    "tokio-native-tls",
    "blocking",
    "stream",
] }
anyhow = "1.0.86"
shinkai_tools_runner = { version = "0.7.19" }

[dependencies.serde]
version = "1.0.188"
features = ["derive"]
