version: '3.9'

services:
  text-embeddings-router:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-latest
    container_name: text-embeddings-router
    restart: "always"
    command: --hostname 0.0.0.0 --port 9081 --model-id sentence-transformers/all-MiniLM-L6-v2 --revision refs/pr/21 --dtype float32
    volumes:
      - embeddings-models:/data
    networks:
      - shinkai
    ports:
      - 9081:9081/tcp
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"

  shinkai-node:
    image: dcspark/shinkai-node:latest
    container_name: shinkai-node
    restart: "always"
    environment:
      - GLOBAL_IDENTITY_NAME=@@localhost.shinkai
      - FIRST_DEVICE_NEEDS_REGISTRATION_CODE=false
      - STARTING_NUM_QR_PROFILES=0
      - STARTING_NUM_QR_DEVICES=0
      - INITIAL_AGENT_NAMES=${INITIAL_AGENT_NAMES:-openai_gpt,openai_gpt_vision}
      - INITIAL_AGENT_MODELS=${INITIAL_AGENT_MODELS:-openai:gpt-4-1106-preview,openai:gpt-4-vision-preview}
      - INITIAL_AGENT_URLS=${INITIAL_AGENT_URLS:-https://api.openai.com,https://api.openai.com}
      - INITIAL_AGENT_API_KEYS=${INITIAL_AGENT_API_KEYS}
      - EMBEDDINGS_SERVER_URL=http://text-embeddings-router:9081/
      - NODE_STORAGE_PATH=storage
      - NODE_IP=0.0.0.0
      - NODE_PORT=9552
      - PING_INTERVAL_SECS=10
      - NODE_API_IP=0.0.0.0
      - NODE_API_PORT=9550
      - NODE_WS_PORT=9551
      - LOG_SIMPLE=true
      - LOG_ALL=true
      - RUST_LOG=info
    volumes:
      - shinode-storage:/app/storage
    networks:
      - shinkai
    ports:
      - 9550:9550/tcp
      - 9551:9551/tcp
      - 9552:9552/tcp
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"

volumes:
  shinode-storage:
    name: shinode-storage
  embeddings-models:
    name: embeddings-models

networks:
  shinkai:
    name: shinkai
