[package]
name = "shinkai_sheet"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true, features = ["full"] }
dashmap = "5.5.3"
chrono = { workspace = true, features = ["serde"] }
uuid = { workspace = true, features = ["v4"] }
regex = { workspace = true }
shinkai_dsl = { workspace = true }
shinkai_message_primitives = { workspace = true }
async-channel = "1.6.1"
blake3 = { workspace = true }

[dependencies.serde]
workspace = true
features = ["derive"]

[[test]]
name = "sheet_common_tests"
path = "tests/sheet_common_tests.rs"

[[test]]
name = "sheet_one_row_advanced_tests"
path = "tests/sheet_one_row_advanced_tests.rs"
