Generated by cbindgen

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct InboxNameWrapper InboxNameWrapper;

struct InboxNameWrapper *inbox_name_wrapper_new(const char *name);

const char *inbox_name_wrapper_get_value(const struct InboxNameWrapper *wrapper);

void inbox_name_wrapper_free(struct InboxNameWrapper *wrapper);

const char *inbox_name_wrapper_get_unique_id(const struct InboxNameWrapper *wrapper);

struct InboxNameWrapper *inbox_name_wrapper_create_regular_inbox_name(const char *sender,
                                                                      const char *sender_subidentity,
                                                                      const char *recipient,
                                                                      const char *recipient_subidentity,
                                                                      bool is_e2e);

struct InboxNameWrapper *inbox_name_wrapper_create_job_inbox_name(const char *unique_id);

char *calculate_blake3_hash_c(const char *input);

void free_calculate_blake3_hash_c_result(char *s);
