[package]
name = "shinkai_http_api"
version = "0.8.13"
edition = "2021"

[dependencies]
utoipa = "4.2.3"
utoipa-swagger-ui = "7.1.0"
chrono = "0.4"
bytes = "1.7.1"
warp = { version = "0.3.7", features = ["compression-gzip", "tls"] }
serde_json = "1.0.117"
futures = "0.3.30"
async-channel = "1.6.1"
x25519-dalek = { version = "2.0.0", features = ["static_secrets"] }
ed25519-dalek = "2.1.0"
shinkai_message_primitives = { workspace = true }
shinkai_tools_primitives = { workspace = true }
reqwest = { version = "0.11.26", features = [
    "json",
    "tokio-native-tls",
    "blocking",
    "stream",
] }
tokio = { version = "1.36.0", features = ["full"] }
tokio-rustls = "0.23"
rustls = "0.20"
hyper = { version = "0.14.30", features = ["server"] }
rustls-pemfile = "1.0.3"

[dependencies.serde]
version = "1.0.188"
features = ["derive"]