[package]
name = "shinkai_test_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
shinkai_test_framework = { path = "../shinkai-test-framework" }
