name: Build Docker Image

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type (debug/release)'
        required: true
        default: 'debug'
        type: choice
        options:
          - debug
          - release
      tag:
        description: 'Docker image tag (e.g. v0.9.10)'
        required: true
        type: string
        default: 'latest'

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    name: Build Docker image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./cloud-node/Dockerfile
          push: true
          build-args: |
            BUILD_TYPE=${{ inputs.build_type }}
          tags: |
            dcspark/shinkai-node:${{ inputs.tag }}
            dcspark/shinkai-node:${{ inputs.build_type }}-latest
