name: Docker Build

on:
  push:
    branches:
      - devops # Change this to your main branch name or desired trigger

jobs:
  build_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.wasm
          push: false # Set push to false to avoid pushing the image
          tags: wasm-tests # Replace with your Docker Hub username and repository name
