name: Deploy LibP2P Relayer

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type (debug/release)'
        required: true
        default: 'release'
        type: choice
        options:
          - debug
          - release
      tag:
        description: 'Docker image tag (e.g. v0.9.10)'
        required: true
        type: string
        default: 'latest'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy LibP2P Relayer
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./shinkai-libs/shinkai-libp2p-relayer/Dockerfile
          push: true
          build-args: |
            BUILD_TYPE=${{ inputs.build_type }}
          tags: |
            dcspark/shinkai-libp2p-relayer:${{ inputs.tag }}
            dcspark/shinkai-libp2p-relayer:${{ inputs.build_type }}-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Summary
        run: |
          echo "🚀 Deployment completed successfully!"
          echo "📦 Image: dcspark/shinkai-libp2p-relayer:${{ inputs.tag }}"