name: PR Check

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Check PR
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Cache cargo assets
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: build-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: (Linux) Install build deps
        if: ${{ matrix.arch == 'x86_64-unknown-linux-gnu' }}
        run: |
          sudo apt-get install -y protobuf-compiler

      - name: build workspace
        run: cargo build --workspace

      - name: build workspace
        run: cargo test -- --test-threads=1
        env:
          IS_TESTING: 1
          WELCOME_MESSAGE: false
          FROM_WALLET_MNEMONICS: ${{ secrets.FROM_WALLET_MNEMONICS }}
          FROM_WALLET_PRIVATE_KEY: ${{ secrets.FROM_WALLET_PRIVATE_KEY }}
